
SCREEN_WIDTH = 1800 
SCREEN_HEIGHT = 1200

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 450

PLAYER_SPEED = 500

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.4
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
 
PLAYER_SHOOT_SPEED = 800
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
